In [2]:
# Packages
import pandas as pd
import statistics 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

#### Session 1

1. We will first learn how to open datafiles in a csv (i.e., comma separated values) format. They are read into dataframes in Python which have a table-like structure.

In [3]:
# opening a csv datafile into a dataframe
tweets_df = pd.read_csv('tweets.csv')

# (n is the number of rows you want it to show)
display(tweets_df.head(n = 20))

# structure of a dataframe (prints the number of rows and number of columns of the data frame)
tweets_df.shape

,Unnamed: 0,user_id,status_id,created_at,screen_name,text,source,display_text_width,reply_to_status_id,reply_to_user_id,...,verified,profile_url,profile_expanded_url,account_lang,profile_banner_url,profile_background_url,profile_image_url,sentiment_score,sentiment_polarity,trust_score
0,0,4.257743e+08,1.349870e+18,1610668808,DeidreBrock,but this is where we are now - https://t.co/Vw...,TweetDeck,54,1.349860e+18,4.257743e+08,...,True,https://t.co/Asy2B4sr7E,http://dbrockmp.scot,NaN,https://pbs.twimg.com/profile_banners/42577429...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/8732115814...,1,2,35
1,1,3.028315e+09,1.349870e+18,1610668854,PeterGrantMP,Retweeting because sometimes a wee bit of unex...,Twitter for iPad,83,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,2,2,85
2,2,1.418358e+09,1.349870e+18,1610668936,VotePursglove,üó£Ô∏è If you are a victim of domestic abuse you c...,Twitter Web App,140,9.999000e+03,NaN,...,True,http://t.co/CdWygVeOQn,http://www.votepursglove.co.uk,NaN,https://pbs.twimg.com/profile_banners/14183580...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1255509092...,3,2,123
3,3,2.373415e+08,1.349870e+18,1610669156,BellRibeiroAddy,The Tories are coming for workers' rights. It'...,Twitter for iPhone,140,9.999000e+03,NaN,...,True,https://t.co/5pBRF80oIm,https://www.youtube.com/channel/UCar93Fgo3nrEG...,NaN,https://pbs.twimg.com/profile_banners/23734148...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1196793948...,3,0,133
4,4,3.028315e+09,1.349870e+18,1610669182,PeterGrantMP,Some will gloat that Brexit is destroying the ...,Twitter for iPad,279,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,2,-1,353
5,5,3.028315e+09,1.349870e+18,1610669209,PeterGrantMP,Waiting for someone on @BBCNewsnight to correc...,Twitter for iPad,139,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,2,0,58
6,6,3.028315e+09,1.349870e+18,1610669224,PeterGrantMP,Siri: show me footage of a man detached in eve...,Twitter for iPad,94,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,4,2,101
7,7,1.168648e+08,1.349870e+18,1610669242,michelledonelan,Today the first high street pharmacies start v...,Twitter for iPhone,140,9.999000e+03,NaN,...,True,https://t.co/jmRufg3Cgi,http://www.michelledonelan.co.uk,NaN,https://pbs.twimg.com/profile_banners/11686479...,http://abs.twimg.com/images/themes/theme13/bg.gif,http://pbs.twimg.com/profile_images/1205600355...,4,2,177
8,8,4.323967e+08,1.349870e+18,1610669243,KarlTurnerMP,"‚ÄúI‚Äôm Minister for Children and Families, I spe...",Twitter for iPhone,140,9.999000e+03,NaN,...,True,https://t.co/mdiVYWcG68,http://karlturnermp.org.uk,NaN,https://pbs.twimg.com/profile_banners/43239668...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1294701979...,2,0,67
9,9,1.168648e+08,1.349870e+18,1610669256,michelledonelan,It‚Äôs disappointing that @LibDems are continuin...,Twitter for iPhone,140,9.999000e+03,NaN,...,True,https://t.co/jmRufg3Cgi,http://www.michelledonelan.co.uk,NaN,https://pbs.twimg.com/profile_banners/11686479...,http://abs.twimg.com/images/themes/theme13/bg.gif,http://pbs.twimg.com/profile_images/1205600355...,3,0,166
10,10,4.660908e+07,1.349870e+18,1610669526,AngusMacNeilSNP,@AngusMacNeilSNP Ian Paisley Jr in 2021 = Edwa...,Twitter for Android,128,9.999000e+03,NaN,...,True,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/46609085...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1010247738...,1,-1,116
11,11,3.028315e+09,1.349870e+18,1610669546,PeterGrantMP,And this is how the British government says th...,Twitter for iPad,130,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,4,-1,198
12,12,3.028315e+09,1.349870e+18,1610669701,PeterGrantMP,@TomLondon6 Oh do keep up.\r\n\r\nScotland nev...,Twitter for iPad,87,1.349850e+18,8.935686e+08,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,4,2,82
13,13,1.133790e+18,1.349870e+18,1610669708,DrNeilHudson,We will keep fighting to save @newtonrigg . Mo...,Twitter for Android,206,9.999000e+03,NaN,...,False,https://t.co/cqgLrFfJJ3,http://neilhudson.org.uk,NaN,https://pbs.twimg.com/profile_banners/11337923...,NaN,http://pbs.twimg.com/profile_images/1133794003...,3,-1,140
14,14,4.660908e+07,1.349870e+18,1610669759,AngusMacNeilSNP,@African_Pat @FranceintheUK Some goods go by p...,Twitter for Android,86,1.349860e+18,1.395083e+09,...,True,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/46609085...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1010247738...,4,-2,41
15,15,4.660908e+07,1.349870e+18,1610669808,AngusMacNeilSNP,"Warned about? Nonsense, you sold the pup, you ...",Twitter for Android,111,9.999000e+03,NaN,...,True,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/46609085...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1010247738...,4,1,130
16,16,1.189290e+18,1.349870e+18,1610669811,Bren4Bassetlaw,We are not going to lower the standards of wor...,Twitter for iPhone,140,9.999000e+03,NaN,...,True,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/11892932...,NaN,http://pbs.twimg.com/profile_images/1349654373...,2,-1,163
17,17,3.028315e+09,1.349870e+18,1610669866,PeterGrantMP,@mgoldenmsp ‚ÄúLies to Parliament‚Äù?\r\n\r\nI tak...,Twitter for iPad,140,1.349460e+18,7.286540e+17,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,1,0,64
18,18,3.028315e+09,1.349870e+18,1610669985,PeterGrantMP,So Labour‚Äôs millionaire donors thought somebod...,Twitter for iPad,129,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,3,-1,171
19,19,3.028315e+09,1.349870e+18,1610670146,PeterGrantMP,Workers of the world unite? https://t.co/pQeMc...,Twitter for iPad,27,9.999000e+03,NaN,...,True,https://t.co/jcBLrrcdYE,http://www.petergrant.scot,NaN,https://pbs.twimg.com/profile_banners/30283145...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1223157456...,4,-1,97

(47563, 94)

In [90]:
# EXERCISE: Using the previous code, repeat these steps for the other csv file in the folder called 'organizations.csv'. 
# Call it 'organizations'

In [1]:
# SOLUTION:

2. Once we have the datafile as a dataframe inside our Python file, we can look up variables. Here we look up variables with different levels of measurement (i.e. nominal, ordinal and interval).

In [92]:
# to obtain all the column names in a dataframe
print(tweets_df.columns)

# to look up a particular variable in a dataframe
display(tweets_df['user_id'])

# to look up multiple variables in a dataframe we use a list with the variable names
display(tweets_df[['user_id','display_text_width']])

# these are examples of three different variables: nominal, ordinal, and interval (respectively)
tweets_df[['user_id','sentiment_score','display_text_width']]

Index(['Unnamed: 0', 'user_id', 'status_id', 'created_at', 'screen_name',
       'text', 'source', 'display_text_width', 'reply_to_status_id',
       'reply_to_user_id', 'reply_to_screen_name', 'is_quote', 'is_retweet',
       'favorite_count', 'retweet_count', 'quote_count', 'reply_count',
       'hashtags', 'symbols', 'urls_url', 'urls_t.co', 'urls_expanded_url',
       'media_url', 'media_t.co', 'media_expanded_url', 'media_type',
       'ext_media_url', 'ext_media_t.co', 'ext_media_expanded_url',
       'ext_media_type', 'mentions_user_id', 'mentions_screen_name', 'lang',
       'quoted_status_id', 'quoted_text', 'quoted_created_at', 'quoted_source',
       'quoted_favorite_count', 'quoted_retweet_count', 'quoted_user_id',
       'quoted_screen_name', 'quoted_name', 'quoted_followers_count',
       'quoted_friends_count', 'quoted_statuses_count', 'quoted_location',
       'quoted_description', 'quoted_verified', 'retweet_status_id',
       'retweet_text', 'retweet_created_at', 'retweet_source',
       'retweet_favorite_count', 'retweet_retweet_count', 'retweet_user_id',
       'retweet_screen_name', 'retweet_name', 'retweet_followers_count',
       'retweet_friends_count', 'retweet_statuses_count', 'retweet_location',
       'retweet_description', 'retweet_verified', 'place_url', 'place_name',
       'place_full_name', 'place_type', 'country', 'country_code',
       'geo_coords', 'coords_coords', 'bbox_coords', 'status_url', 'name',
       'location', 'description', 'url', 'protected', 'followers_count',
       'friends_count', 'listed_count', 'statuses_count', 'favourites_count',
       'account_created_at', 'verified', 'profile_url', 'profile_expanded_url',
       'account_lang', 'profile_banner_url', 'profile_background_url',
       'profile_image_url', 'sentiment_score', 'sentiment_polarity',
       'trust_score'],
      dtype='object')

0        4.257743e+08
1        3.028315e+09
2        1.418358e+09
3        2.373415e+08
4        3.028315e+09
             ...
47558    3.028315e+09
47559    3.028315e+09
47560    3.028315e+09
47561    3.028315e+09
47562    3.028315e+09
Name: user_id, Length: 47563, dtype: float64

            user_id  display_text_width
0      4.257743e+08                  54
1      3.028315e+09                  83
2      1.418358e+09                 140
3      2.373415e+08                 140
4      3.028315e+09                 279
...             ...                 ...
47558  3.028315e+09                 158
47559  3.028315e+09                 258
47560  3.028315e+09                  62
47561  3.028315e+09                  67
47562  3.028315e+09                 279

[47563 rows x 2 columns]

            user_id  sentiment_score  display_text_width
0      4.257743e+08                1                  54
1      3.028315e+09                2                  83
2      1.418358e+09                3                 140
3      2.373415e+08                3                 140
4      3.028315e+09                2                 279
...             ...              ...                 ...
47558  3.028315e+09                1                 158
47559  3.028315e+09                2                 258
47560  3.028315e+09                2                  62
47561  3.028315e+09                3                  67
47562  3.028315e+09                3                 279

[47563 rows x 3 columns]

In [ ]:
# EXERCISE: now look up two other variables from the dataset, one nominal and one interval

In [2]:
# SOLUTION: different possible solutions. For example:

3. A part from looking up existing variables, we can also create new variables from existing ones. Here we see an example where we transform an interval variable as well as one where we transform a nominal one.

In [ ]:
# The variable 'display_text_width' indicates the length of the post. We are going to create a new variable 
# called 'relative_length' which will show the length of a post as the percentage of the maximum length.

# We first find the maximum length of a post
max_length = max(tweets_df['display_text_width'])
print(max_length)

# We then create the new variable 
relative_length = tweets_df['display_text_width']/max_length

# We finally add it trelative_lengtho our data set
tweets_df['relative_length'] = relative_length

# As we can see we now have an extra column (i.e. variable) in our dataframe
tweets_df.shape

317

(47563, 95)

In [ ]:
# EXERCISE: Using the code above, create and add a new variable called 'relative_favorite_count'. This variable will show the 
# number of favorites a post got as a percentage of the maximum number of favorites. Use the variable 'favorite_count'
# for this purpose.

In [3]:
# SOLUTION:

In [93]:
# We can also do this sort of transformations on categorical variables. For example, lets create a variable called 
# 'is_apple'"tweets raw.csv" based on the 'source' variable. This variable will have a 'True' value if the source 
# of the post is an Apple device and a 'False' value otherwise. 

apple_list = ['Twitter for iPhone','Twitter for iPad','Tweetbot for iŒüS','Twitterrific for iOS','Twitter for Mac','OS X']
tweets_df['is_apple'] = [False for i in range(tweets_df.shape[0])]
for i in range(tweets_df.shape[0]):
    if tweets_df.loc[i,'source'] in apple_list:
        tweets_df.loc[i,'is_apple'] = True
    
# We can see that more than half of the posts were published from an Apple device
tweets_df['is_apple'].value_counts()

True     29372
False    18191
Name: is_apple, dtype: int64

4. Missing values (a.k.a. NA values, or NaN values) are common in data. They represent cells where the data is, for whatever reason, not available (e.g. because it could not be measured, because for a given case measuring would make no sense). Dealing with missing data is a complicated topic and it will depend greatly on the particular case. In this example we simply show how to make sure that NA values are treated as such in a Python dataframe.

In [ ]:
# Sometimes NA values are not defined as such. For instance, a dataset may have a 9999 value in those cells 
# where data is missing. It is important to rename this values so they are correctly interpreted as NA.  

# We can specify this when we read the data in the first place pd.read_csv(...,na_values=9999) or now by using the replace()
# method.

tweets_df['reply_to_status_id'] = tweets_df['reply_to_status_id'].replace(9999,np.NaN)

# lets see the changes
tweets_df['reply_to_status_id']

0        1.349860e+18
1                 NaN
2                 NaN
3                 NaN
4                 NaN
             ...
47558    1.355850e+18
47559    1.349050e+18
47560    1.356030e+18
47561    1.355930e+18
47562    1.355930e+18
Name: reply_to_status_id, Length: 47563, dtype: float64

In [ ]:
# EXERCISE: by looking up its values identify how missing data is coded in the variable 'retweet_source', and using the code 
# above replace it with NA value (i.e. np.NaN).

In [4]:
# SOLUTION